{
 "title": "Device Electricity Consumption",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "from(bucket: \"Systemstats/autogen\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"power_watts\")\n|> keyValues(keyColumns: [\"host\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Consumption",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\" and r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"${device}\")\n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  |> map(fn: (r) => ({_value: r._value}))\n  \n  "
    }
   ]
  },
  {
   "title": "Current Usage Cost /hr",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "usage = from(bucket: \"Systemstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"${device}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  |> toFloat()\n\n  \ncost = from(bucket: \"Systemstats/rp_720d\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"unit_cost\")\n  |> filter(fn: (r) => r.host == \"power-meter\")\n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> fill(usePrevious:true)\n  \n  \n  \n join(tables: {t1: cost, t2: usage}, on: [\"_time\"])\n   |> map(fn: (r) => ({\n      _value: r._value_t1 * (float(v: r._value_t2) / 1000.0),\n      _time: r._time,\n      device: r.host,\n      _field: \"consumption_cost\"\n   }))\n   //|> last()\n\n"
    }
   ]
  },
  {
   "title": "kWh Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\" and r._field == \"watts_today\")\n  |> filter(fn: (r) => r.host == \"${device}\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 1000.00 }))"
    }
   ]
  },
  {
   "title": "Cost Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "usage = from(bucket: \"Systemstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\" and r._field == \"watts_today\")\n  |> filter(fn: (r) => r.host == \"${device}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  \ncost = from(bucket: \"Systemstats/rp_720d\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"unit_cost\")\n  |> filter(fn: (r) => r.host == \"power-meter\")\n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> map(fn: (r) => ({r with _value: r._value}))\n  \n join(tables: {t1: cost, t2: usage}, on: [\"_time\"])\n   |> map(fn: (r) => ({\n      _value: r._value_t1 * (float(v: r._value_t2) / 1000.0),\n      _time: r._time,\n      device: r.host,\n      _field: \"consumption_cost\"\n   \n   }))\n   |> last()"
    }
   ]
  },
  {
   "title": "Max Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\" and r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"${device}\")\n  |> max()"
    }
   ]
  },
  {
   "title": "Average Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\" and r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"${device}\")\n  |> mean()"
    }
   ]
  },
  {
   "title": "Min Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\" and r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"${device}\")\n  |> min()"
    }
   ]
  },
  {
   "title": "Average Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\" and r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"${device}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> fill(usePrevious: true)\n  "
    }
   ]
  },
  {
   "title": "Cost /hr at current usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "usage = from(bucket: \"Systemstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\" and r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"${device}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  \n\ncost = from(bucket: \"Systemstats/rp_720d\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"unit_cost\")\n  |> filter(fn: (r) => r.host == \"power-meter\")\n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> fill(usePrevious: true)\n  |> map(fn: (r) => ({r with _value: r._value}))\n  \n\n join(tables: {t1: cost, t2: usage}, on: [\"_time\"])\n   |> map(fn: (r) => ({\n      _value: r._value_t1 * (r._value_t2 / 1000.0),\n      _time: r._time,\n      device: r.host,\n      _field: \"consumption_cost\"\n   \n   }))\n   |> fill(usePrevious: true)\n  "
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "usage = from(bucket: \"Systemstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\" and r._field == \"watts_today\")\n  |> filter(fn: (r) => r.host == \"${device}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n  \n\ncost = from(bucket: \"Systemstats/rp_720d\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"unit_cost\")\n  |> filter(fn: (r) => r.host == \"power-meter\")\n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> fill(usePrevious: true)\n  \n  \n\n join(tables: {t1: cost, t2: usage}, on: [\"_time\"])\n   |> map(fn: (r) => ({\n      _value: r._value_t1 * (float(v: r._value_t2) / 1000.0),\n      _time: r._time,\n      device: r.host,\n      _field: \"consumption_cost\"\n   \n   }))\n   |> fill(usePrevious: true)\n  \n  "
    }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"watts_today\")\n  |> filter(fn: (r) => r.host == \"${device}\")\n  |> aggregateWindow(every: 1d, fn: max)"
    }
   ]
  },
  {
   "title": "Daily Cost  ($device)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "usage = from(bucket: \"Systemstats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"watts_today\")\n  |> filter(fn: (r) => r.host == \"${device}\")\n  |> aggregateWindow(every: 1d, fn: max)\n  \n\ncost = from(bucket: \"Systemstats/rp_720d\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"unit_cost\")\n  |> filter(fn: (r) => r.host == \"power-meter\")\n  |> group()\n  |> aggregateWindow(every: 1d, fn: mean)\n  \n  \n\n join(tables: {t1: cost, t2: usage}, on: [\"_time\"])\n   |> map(fn: (r) => ({\n      _value: r._value_t1 * (float(v: r._value_t2) / 1000.0),\n      _time: r._time,\n      _field: \"consumption_cost\"\n   \n   }))\n   |> fill(usePrevious: true)"
    }
   ]
  }
 ]
}